[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile"
buildContext = "api"

[deploy]
startCommand = "dotnet WebOnlyAPI.dll"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
